---
title: "Easyabx results editing"
output: html_document
---
```{r}
library(plyr)
library(ggplot2)
library(wesanderson)
```

```{r}
## ABXpy tests

read_abxpy <- function(data_folder) {
  # Files utilisés
  distances <- readr::read_delim(paste0(data_folder, "/distance.txt"), " ")
  items <- readr::read_delim(paste0(data_folder, "/abx.item"), " ")
  
  distances$X1 <- NULL
  
  # Change column names because why not
  names(distances)[which(names(distances)=="d(A, B)")] <- "dist"

  ####################
  items_B <- dplyr::select(distances, dplyr::ends_with("_B"))
  items_B_ <- dplyr::inner_join(items_B, items,
                                    by=c(file_B="#file", onset_B="onset", 
                                         offset_B="offset"))
  items_B__ <- dplyr::rename_at(items_B_, 
                  names(items_B_)[!endsWith(names(items_B_), "_B")], 
                  function(x) paste0(x, "_B"))
  items_B_clean <- items_B__
  items_B_clean$type_B <- NULL
  items_B_clean$vowel_B <- NULL
  items_B_clean$position_B <- NULL
  items_B_clean$new_B <- NULL

  items_A <- dplyr::select(distances, dplyr::ends_with("_A"))
  items_A_ <- dplyr::inner_join(items_A, items,
                                    by=c(file_A="#file", onset_A="onset", 
                                         offset_A="offset"))
  items_A__ <- dplyr::rename_at(items_A_, 
                  names(items_A_)[!endsWith(names(items_A_), "_A")], 
                  function(x) paste0(x, "_A"))
  items_A_clean <- items_A__
  items_A_clean$type_A <- NULL
  items_A_clean$vowel_A <- NULL
#  items_A_clean$position_A <- NULL
  items_A_clean$new_A <- NULL

  # Selectionne le distance score
  distance_score <- dplyr::select(distances, "dist")

  # Met tout dans un meme tibble
  distances_better <- dplyr::bind_cols(items_A_clean, items_B_clean, distance_score)
  distances_better$onset_A <- NULL
  distances_better$offset_A <- NULL
  distances_better$onset_B <- NULL
  distances_better$offset_B <- NULL
  # Create a new table with less information                   
  names(distances_better)[which(names(distances_better)=="#item_A")] <- "item_A"
  names(distances_better)[which(names(distances_better)=="#item_B")] <- "item_B"
  
  distances_better$ejective_A <- grepl(">", distances_better$sequence_A)
  distances_better$ejective_B <- grepl(">", distances_better$sequence_B)
  
  distances_better <- dplyr::mutate(distances_better,
                                    same=ifelse(ejective_A == ejective_B,
                                                "SAME", "DIFFERENT"))
#  for(i in 1:nrow(distances_better)){
#    
#    if(distances_better[i,24] == "DIFFERENT"){
#    distances_better[i,25] <- "different"
#  } else if((distances_better[i,24] == "SAME")&(distances_better[i,23] == "FALSE")){
#    distances_better[i,25] <- "pulmonic"
#  } else if((distances_better[i,24] == "SAME")&(distances_better[i,23] == "TRUE")){
#    distances_better[i,25] <- "ejective"
#  }
#
#  }

  return(distances_better)
}

```

```{r}
## Easy_abx tests
# Ne pas oublier d'ajouter 2 a dans abx.item et 4 dans distance.txt

read_easyabx <- function(data_folder) {
  # Files utilisés
  distances <- readr::read_delim(paste0(data_folder, "/distance.txt"), " ")
  #distances <- readr::read_delim("../results/features/no_vot___by__place_position_question_speaker_vowel/distance.txt", " ")
  
  ## ici deux problèmes : 
  ## soit j'utilise le remplacement des caractères qui lient les items et j'ai trop de colonnes
  ## soit je le fais pas et j'ai deux colonnes nom_onset_offset et quatre noms de colonnes random
  ## dans tous les cas, trouver comment aligner les headers et les colonnes
  
  items <- readr::read_delim(paste0(data_folder, "/abx.item"), " ")
  #items <- readr::read_delim("../results/features/no_vot___by__place_position_question_speaker_vowel/abx.item", " ")
  
  # Suppress row numbers
  distances$X1 <- NULL
  
  # Get rid of random times in distances
  distances$a <- NULL
  distances$a_1 <- NULL
  distances$a_2 <- NULL
  distances$a_3 <- NULL
  
  # Change column names because why not
  names(distances)[which(names(distances)=="d(A, B)")] <- "dist"

  # Get rid of random times in items
  items$a <- NULL
  items$a_1 <- NULL
  
  ####################
  items_B <- dplyr::select(distances, dplyr::ends_with("_B"))
  items_B_ <- dplyr::inner_join(items_B, items,
                                    by=c(file_B="#file", onset_B="onset", 
                                         offset_B="offset"))
  items_B__ <- dplyr::rename_at(items_B_, 
                  names(items_B_)[!endsWith(names(items_B_), "_B")], 
                  function(x) paste0(x, "_B"))

  items_B_clean <- items_B__
  items_B_clean$type_B <- NULL
  items_B_clean$vowel_B <- NULL
  items_B_clean$position_B <- NULL
  items_B_clean$`#syllables_B` <- NULL

  items_A <- dplyr::select(distances, dplyr::ends_with("_A"))
  items_A_ <- dplyr::inner_join(items_A, items,
                                    by=c(file_A="#file", onset_A="onset", 
                                         offset_A="offset"))
  items_A__ <- dplyr::rename_at(items_A_, 
                  names(items_A_)[!endsWith(names(items_A_), "_A")], 
                  function(x) paste0(x, "_A"))
  items_A_clean <- items_A__

  items_A_clean$type_A <- NULL
  items_A_clean$vowel_A <- NULL
#  items_A_clean$position_A <- NULL
  items_A_clean$`#syllables_A` <- NULL

  # Selectionne le distance score
  distance_score <- dplyr::select(distances, "dist")

  # Met tout dans un meme tibble
  distances_better <- dplyr::bind_cols(items_A_clean, items_B_clean, distance_score)
  distances_better$onset_A <- NULL
  distances_better$offset_A <- NULL
  distances_better$onset_B <- NULL
  distances_better$offset_B <- NULL
  # Create a new table with less information                   
  names(distances_better)[which(names(distances_better)=="#sequence_A")] <- "sequence_A"
  names(distances_better)[which(names(distances_better)=="#sequence_B")] <- "sequence_B"

  distances_better$ejective_A <- grepl(">", distances_better$sequence_A)
  distances_better$ejective_B <- grepl(">", distances_better$sequence_B)
  
  distances_better <- dplyr::mutate(distances_better,
                                    same=ifelse(ejective_A == ejective_B,
                                                "SAME", "DIFFERENT"))
#  for(i in 1:nrow(distances_better)){
#    
#    if(distances_better[i,16] == "DIFFERENT"){
#    distances_better[i,17] <- "different"
#  } else if((distances_better[i,16] == "SAME")&(distances_better[i,15] == "FALSE")){
#    distances_better[i,17] <- "pulmonic"
#  } else if((distances_better[i,16] == "SAME")&(distances_better[i,15] == "TRUE")){
#    distances_better[i,17] <- "ejective"
#  }
#
#  }

  #names(distances_better[,17]) <- "summary"

  return(distances_better)
}

```


```{r warning = FALSE}
setwd("~/ejectives_abx/results")

distances_fixed_standard <- read_abxpy("fixed/by__place_position_question_speaker_vowel")
distances_fixed_standard$experiment <- "fixed_standard"

all_fixed_standard <- read_abxpy("fixed_initial_medial/by__place_position_question_speaker_vowel")
all_fixed_standard$experiment <- "all_fixed_standard"

distances_abxpy_egg <- read_abxpy("egg_fixed/abxpy_mel_by__place_position_question_speaker_vowel")
distances_abxpy_egg$experiment <- "egg_abxpy"

distances_abxpy_egg_40 <- read_abxpy("egg_fixed/abxpy_mel40_by__place_position_question_speaker_vowel")
distances_abxpy_egg_40$experiment <- "egg_abxpy_mel40"

distances_abxpy_egg_25 <- read_abxpy("egg_fixed/abxpy_mel25_by__place_position_question_speaker_vowel")
distances_abxpy_egg_25$experiment <- "egg_abxpy_mel25"

# distances_egg <- read_easyabx("egg_fixed/by__place_position_question_speaker_vowel")
# distances_egg$experiment <- "egg"

distances_features_with_vot <- read_easyabx("features/by__place_position_question_speaker_vowel")
distances_features_with_vot$experiment <- "features_with_vot"

distances_features_no_vowel_timbre <- read_easyabx("features/by__place_position_question_speaker")
distances_features_no_vowel_timbre$experiment <- "features_no_vowel_timbre"

# distances_features_vot_only <- read_easyabx("features/vot_only___by__place_position_question_speaker_vowel")
# distances_features_vot_only$experiment <- "features_only_vot"
# 
# distances_features_vot_vowel_duration <- read_easyabx("features/vot_vowel_duration_by__place_position_question_speaker_vowel")
# distances_features_vot_vowel_duration$experiment <- "features_vot_vowel_duration"
#distances_better$experiment <- "euclidian_vot"
# distances_deltas_egg <- read_easyabx("egg_fixed/deltas__by__place_position_question_speaker_vowel")
# distances_deltas_egg$experiment <- "deltas_egg"
# 
# distances_deltas_log_egg <- read_easyabx("egg_fixed/deltas_log2__by__place_position_question_speaker_vowel")
# distances_deltas_log_egg$experiment <- "deltas_log2_egg"
# 
# distances_deltas_log_absolute_egg <- read_easyabx("egg_fixed/deltas_log2_absolute__by__place_position_question_speaker_vowel")
# distances_deltas_log_absolute_egg$experiment <- "deltas_log2_absolute_egg"
# 
# distances_deltas_carre_egg <- read_easyabx("egg_fixed/deltas_carre__by__place_position_question_speaker_vowel")
# distances_deltas_carre_egg$experiment <- "deltas_carre_egg"

## Tous les tests dans un même fichier
#distances <- dplyr::bind_rows(distances_fixed_standard, distances_features_vot_only)
distances <- dplyr::bind_rows(distances_fixed_standard, all_fixed_standard)

#distances <- distances_egg_1000
distances$place <- distances$place_A # know this because experiment was BY place, speaker
distances$speaker <- distances$speaker_A 
distances$question <- distances$question_A 

```


```{r}
# Plot the distances by experiment
ggplot(all_fixed_standard, aes(x = position_A, y = dist, fill = same)) +
      ggplot2::geom_boxplot(position=position_dodge(width = .8)) +
      ggplot2::facet_grid(speaker_A ~ place_A) +
      ggplot2::theme_minimal() +
      ggplot2::scale_fill_manual(values = wes_palette(n=2, name = "GrandBudapest"))

#ggsave("/Users/chloe/euclidian_vot_and_abxpy.jpeg", width = 5, height = 5)

ggplot(distances, aes(x = place, y = dist, fill=same)) + 
      ggplot2::geom_violin(position="dodge") +
      ggplot2::facet_grid(speaker ~ experiment) +
      ggplot2::theme_minimal() +
      ggplot2::labs(title = "", 
                    x = "Point d'articulation", 
                    y = "Dynamic Time Warping") +
      ggplot2::ylim(c(0, 0.12)) +
      ggplot2::scale_fill_manual(values = wes_palette(n=2, name="Darjeeling"))

#ggsave("/Users/chloe/abxpy_fixed.jpeg", width = 10, height = 5)
```

```{r}
# Do a scatter plot of dtw and vot distances to see how much they are correlated
tmp_vot <- distances_features_vot_only
tmp_vot$dist_vot <- tmp_vot$dist
tmp_vot$dist <- NULL

tmp_fixed <- distances_fixed_standard
tmp_fixed$dist_fixed <- tmp_fixed$dist
tmp_fixed$dist <- NULL

distance_correlation <- dplyr::inner_join(tmp_vot, tmp_fixed, 
                                         by=c(file_A="file_A", file_B="file_B",
                                              sequence_A="sequence_A", sequence_B="sequence_B",
                                              place_A="place_A", speaker_A="speaker_A", 
                                              same="same"))

                                              
ggplot(distance_correlation, aes(x=dist_vot, y=dist_fixed)) +
  ggplot2::geom_point() +
  geom_smooth(method=lm)

#ggsave("/Users/chloe/scatterplot_vot_and_abxpy.jpeg", width = 5, height = 5)
```

