---
title: "Cosine similarity"
output: html_document
---

Convert row > column to calculate cosine similarity
https://cran.r-project.org/web/packages/lsa/lsa.pdf

```{r}
library(lsa)
```

```{r}
# Mise en forme des données d'amplitudes
#egg_data <- readr::read_delim("../results/egg_fixed/egg_1000_edit.csv", ",")

# Supprimer les données qui ne sont pas des mesures d'amplitude
#amplitudes <- dplyr::select(egg_data, dplyr::starts_with("time"))
#colonnes <- as.vector(egg_data$`#file`)
#egg <- as.data.frame(t(amplitudes))
#colnames(egg) <- colonnes

# ###############
# # Mise en forme des deltas après création des deltas
# egg_data <- readr::read_delim("../results/egg_fixed/egg_deltas.csv", ",")
# 
# # Supprimer les données qui ne sont pas des mesures d'amplitude
# amplitudes <- dplyr::select(egg_data, dplyr::starts_with("delta"))
# colonnes <- as.vector(egg_data$`#file`)
# egg <- as.data.frame(t(amplitudes))
# colnames(egg) <- colonnes

###############
# Mise en forme des deltas après création des deltas
features_data <- readr::read_delim("../results/features/abx.csv", ",")

# Supprimer les données qui ne sont pas des mesures d'amplitude
#vot <- dplyr::select(features_data, dplyr::starts_with("vot"))
vowel_dur <- dplyr::select(features_data, dplyr::starts_with("voweln"))
#measures <- dplyr::bind_cols(vot, vowel_dur)
measures <- vowel_dur
colonnes <- as.vector(features_data$`#file`)
features <- as.data.frame(t(measures))
colnames(features) <- colonnes
```

```{r}
# original <- readr::read_delim("../results/egg_fixed/egg_1000/distance.txt", " ")
# 
# noms_fichiers <- dplyr::select(original, dplyr::starts_with("file"))
# distance <- dplyr::select(original, dplyr::starts_with("d"))
# modifie <- dplyr::bind_cols(noms_fichiers, distance)
# modifie$dis2txt <- modifie$`d(A, B)`
# modifie$`d(A, B)` <- NULL
# 
# # Calcul des similarités cosinus
# for(i in 1:nrow(modifie)) {
#   
#     a <- modifie[i,1]
#     b <- modifie[i,2]
#     c <- dplyr::select(egg, dplyr::matches(as.character(a)))
#     d <- dplyr::select(egg, dplyr::matches(as.character(b)))
#     df <- as.matrix(dplyr::bind_cols(c, d))
#     e <- cosine(df)
#     modifie[i,4] <- e[1,2]
#   
#     }
# 
# names(modifie)[4] <- "cosine"
# 
# modifie$difference <- modifie$dis2txt + modifie$cosine
# # = 1
# 
# write.csv(modifie, "../results/egg_fixed/dis2txt_and_cosine_similarity.csv", row.names = F)
```

```{r}
original <- readr::read_delim("../results/features/vot_only___by__place_position_question_speaker_vowel/distance.txt", " ")

noms_fichiers <- dplyr::select(original, dplyr::starts_with("file"))
distance <- dplyr::select(original, dplyr::starts_with("d"))
modifie <- dplyr::bind_cols(noms_fichiers, distance)
modifie$dis2txt <- modifie$`d(A, B)`
modifie$`d(A, B)` <- NULL

# # Calcul des similarités cosinus
# for(i in 1:nrow(modifie)) {
#   
#     a <- modifie[i,1]
#     b <- modifie[i,2]
#     c <- dplyr::select(features, dplyr::matches(as.character(a)))
#     d <- dplyr::select(features, dplyr::matches(as.character(b)))
#     df <- as.matrix(dplyr::bind_cols(c, d))
#     e <- cosine(df)
#     modifie[i,4] <- e[1,2]
#   
# }

# Calcul des distances euclidiennes
for (i in 1:nrow(modifie)) {
  
    a <- modifie[i,1]
    b <- modifie[i,2]
    c <- as.numeric(dplyr::select(features, dplyr::matches(as.character(a))))
    d <- as.numeric(dplyr::select(features, dplyr::matches(as.character(b))))
    e <- dist(rbind(c, d))
    modifie[i,4] <- e
}

names(modifie)[4] <- "euclidian"

modifie$difference <- modifie$dis2txt + modifie$cosine
# = 1

write.csv(modifie, "../results/egg_fixed/dis2txt_and_cosine_similarity_vot_only.csv", row.names = F)

```

```{r}
# Corrélation entre dis2txt scores et similarité cosinus ?
scores <- readr::read_delim("../results/egg_fixed/dis2txt_and_cosine_similarity.csv", ",")

# Yup, c'est la même chose
ggplot(scores, aes(x = dis2txt, y = cosine)) + 
  ggplot2::geom_point()
```

```{r}
# Cross correlation?
# Pulmonic vs ejective; cosine similarity = -0.602380585
essai <- ccf(egg$geo020s08a0136v02, egg$geo020s08a0202v02, type = "correlation")
essaiefnsdlkn<- ccf(egg$geo020s08a0202v02, egg$geo020s08a0202v02, type = "correlation")
# Ejective vs ejective; cosine similarity = 0.886472351
essai_ <- ccf(egg$geo020s09a0057v01, egg$geo020s09a0098v01, type = "correlation")

# Null correlation; ke-ke cosine similarity = 0.002656558
essai__ <- ccf(egg$geo020s08a0135v02, egg$geo020s08a0136v02, type = "correlation")
```

